# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 51ab46617a89e38510d44970ac265b1d184d68c40d68735eace4ac6050fbe7c5556bf2da517682140a46bb7fbd2b98a4df6c314b946e7aeddb8c7f58b886aa5d

test:
  secret_key_base: 5b615b5d1882201cad8fbb9e422b523b00ffa27ff6ba0e3e123da345dff2dd782200015b96af8ca58c7d31591dee20bdb794affa3854fe6552c331d8d9b85672

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
